# Generated by Django 2.1.7 on 2019-03-27 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Choice Data',
            },
        ),
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Question Data',
            },
        ),
        migrations.CreateModel(
            name='TrackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Track Data',
            },
        ),
        migrations.AddField(
            model_name='questiondata',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.TrackData'),
        ),
        migrations.AddField(
            model_name='choicedata',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.QuestionData'),
        ),
    ]
